spring:
  application:
    name: RealTimeDocCollab
  datasource:
    url: jdbc:postgresql://localhost:5432/RealTimeDocCollab
    username: postgres
    password: 076493
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: V6fTF1MzMy9RZTvoV7x7VoVGLXmgtVXHUdMOAHyn6Wg=